# Generated by Django 2.2.13 on 2020-07-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_Habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_garage',
            name='estado_stuff',
            field=models.CharField(blank=True, choices=[('desgastado', 'usado'), ('maltratado', 'funcional')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta_garage',
            name='tipy_fields',
            field=models.CharField(blank=True, choices=[('bedroom', 'cuarto'), ('kitchen', 'cocina'), ('garage', 'garage'), ('bathroom', 'baño')], max_length=100, null=True),
        ),
    ]
